# Generated by Django 3.0.7 on 2020-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(default='/photos/logo_Sakana.jpg', upload_to='photos/'),
        ),
    ]
