# Generated by Django 3.0.7 on 2020-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0005_extensionuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionuser',
            name='nb_trials',
            field=models.IntegerField(default=5),
        ),
    ]
